spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

blog_engine:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005