spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/blog-engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&amp&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qweqwe
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tyunyaevds@gmail.com
    password:
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
      mail.smtp.timeout: 10000
  #logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

blog_engine:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  additional:
    announceMaxLength: 150
    uploadedMaxFileWeight: 5242880 # TODO разделить файл для комментов и файл для профиля?
    commentMinLength: 3
    passwordMinLength: 6
    profilePhotoWidth: 36
    profilePhotoHeight: 36
    websiteHost: localhost
  cloudinary:
    cloudName: skillbox
    apiKey:
    apiSecret: